splash = false
wallpaper {
	monitor = HDMI-A-1
	path = ~/Wallpapers/Christian/orthodox-roof.png
	fit_mode = cover
}
wallpaper {
	monitor = eDP-1
	path = ~/Wallpapers/Christian/orthodox-roof.png
	fit_mode = cover
}
