# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="bira"
plugins=(
  git
  rust
  #tmux
  sudo
#  thefuck
  colored-man-pages
)


#Tmux oh-my-zsh plugin
#ZSH_TMUX_AUTOSTART=true


# Set default editor
export EDITOR="nvim"
export VISUAL="nvim"
export SUDO_EDITOR="nvim"
alias vim="nvim"

# For java windows
export _JAVA_AWT_WM_NONREPARENTING=1

# Updates
alias updateP="sudo pacman -Syu"
alias updateY="yay -Syu"

# Bluetooth
alias start_bt="sudo systemctl start bluetooth && sudo systemctl enable bluetooth"
alias stop_bt="sudo systemctl stop bluetooth && sudo systemctl disable bluetooth"
alias status_bt="systemctl status bluetooth.service"

# Custom Aliases
alias steam="flatpak run com.valvesoftware.Steam &"
alias rgb="openrgb &"
alias unixp="clear ; neofetch"
#alias clock="peaclock"
alias lz="eza --icons"
alias windows="~/helpful/windows.sh"
alias cat="bat"

# Github
alias getDots="clear ; git clone https://github.com/faraday22/dotfiles ; cd dotfiles"
alias rmDots="clear ; cd ~ ; rm -rf dotfiles"
alias lg="lazygit"

# swaylock-effects
alias lock="swaylock --clock --effect-blur 7x5 --fade-in 0.3 --indicator --grace 2.5 --screenshots --ring-color bb00cc"

# Media Types
alias img="sxiv"
alias video="vlc"
alias audio="~/helpful/audioControl.sh"
# Screenshots
alias ss="~/helpful/screenshot.sh"
alias ms="~/helpful/getMcShots.sh"

# Check if running interactively before executing further commands
[[ $- != *i* ]] && return
alias grep='grep --color=auto'

source $ZSH/oh-my-zsh.sh
