# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="jaischeema"
plugins=(
  git
  zsh-autosuggestions
  colored-man-pages
  rust
)


# Set default editor
export EDITOR="nvim"
export VISUAL="nvim"

# For java windows
export _JAVA_AWT_WM_NONREPARENTING=1

# Bluetooth
alias start_bluetooth="sudo systemctl start bluetooth && sudo systemctl enable bluetooth"
alias stop_bluetooth="sudo systemctl stop bluetooth && sudo systemctl disable bluetooth"


# Custom Aliases
alias rgb="openrgb &"
alias unixp="clear ; neofetch"
alias vim="nvim"
alias lock="swaylock"
alias img="sxiv"
alias video="vlc"
alias audio="~/helpful/audioControl.sh"
alias ss="~/helpful/screenshot.sh"
alias ms="~/helpful/getMcShots.sh"
alias mlogin="~/personal/AutoMCLog/main.sh"
alias clock="peaclock"
alias lz="eza --icons -F -l"
alias windows="~/helpful/windows.sh"
alias cat="bat"
alias lg="lazygit"

# Check if running interactively before executing further commands
[[ $- != *i* ]] && return
alias ls='ls --color=auto'
alias grep='grep --color=auto'




source $ZSH/oh-my-zsh.sh
